### ISSUE TITLE
Ensure outside contributors can run integration tests

### ISSUE THREAD

**Issue by KevinGDialpad** [talkiq/gcloud-rest#36]
Same as https://github.com/talkiq/gcloud-aio/issues/53 - adding it here so we don't forget

A workaround is to use a GAE project you have access to. Not ideal because that project is unrelated to gcloud-rest.

**Comment by TheKevJames** [comment]
I've been working on a good way to do this with the Google folks; no solution yet, but we've got some ideas to try out.

**Comment by TheKevJames** [comment]
Closing all issues on this repo, as it has been subsumed by [gcloud-aio](github.com/talkiq/gcloud-aio)
